import type { Metadata } from "next";
import "./globals.css";
import { Button } from "@/components/button";
import { IconButton } from "@/components/icon-button";
import { InputField, InputIcon, InputRoot } from "@/components/input";
import { ArrowRight, Copy, Mail } from "lucide-react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				{children}
				<Button>
					Enviar
					<ArrowRight />
				</Button>

				<IconButton>
					<Copy />
				</IconButton>

				<div>
					<InputRoot>
						<InputIcon>
							<Mail />
						</InputIcon>
						<InputField />
					</InputRoot>
				</div>
			</body>
		</html>
	);
}
